'use client'

import { useEffect, useRef } from 'react'

/**
 * Shared 6-box numeric input atom used by both the OTP and soft-token
 * verification screens. Renders a row of digit slots backed by a single
 * hidden text input — that arrangement preserves browser/OS one-time-code
 * autofill (`autocomplete="one-time-code"`, iOS keyboard suggestion bar)
 * which a multi-input row would lose.
 */
interface NativeOTPInputProps {
  value: string
  maxLength: number
  onChange: (next: string) => void
  /** Auto-focus the hidden input on mount. Defaults to `true`. */
  autoFocus?: boolean
  /**
   * Hint browsers / OS to surface the SMS-OTP autofill UI. Defaults to
   * `true`. Disable for flows where there is no incoming code (e.g. soft
   * tokens generated by the user's authenticator app).
   */
  enableAutoFill?: boolean
}

export default function NativeOTPInput({
  value,
  maxLength,
  onChange,
  autoFocus = true,
  enableAutoFill = true,
}: NativeOTPInputProps) {
  const hiddenRef = useRef<HTMLInputElement>(null)
  const digits = Array.from({ length: maxLength }, (_, i) => value[i] || '')

  const focusInput = () => hiddenRef.current?.focus()

  useEffect(() => {
    if (!autoFocus) return
    // Mobile browsers can be picky about immediate focus on mount.
    // A short delay improves reliability for keyboard + OTP suggestions.
    const t = window.setTimeout(() => focusInput(), 150)
    return () => window.clearTimeout(t)
  }, [autoFocus])

  return (
    <div className="relative w-full">
      <input
        ref={hiddenRef}
        type="tel"
        inputMode="numeric"
        autoComplete={enableAutoFill ? 'one-time-code' : 'off'}
        name={enableAutoFill ? 'one-time-code' : undefined}
        pattern="\d*"
        enterKeyHint="done"
        maxLength={maxLength}
        value={value}
        onChange={(e) => {
          const cleaned = e.target.value.replace(/\D/g, '').slice(0, maxLength)
          onChange(cleaned)
        }}
        // Keep the input out of the layout so it never blocks taps on other fields.
        className="absolute -left-[9999px] top-0 w-px h-px opacity-0"
      />

      <div
        className="flex gap-2.5 w-full px-5 justify-center"
        onClick={focusInput}
      >
        {digits.map((digit, i) => {
          const isCursor = i === value.length && value.length < maxLength
          return (
            <div
              key={i}
              className={`w-12 h-12 rounded-[10px] border flex items-center justify-center text-base font-semibold text-text-primary shrink-0 transition-colors ${
                isCursor
                  ? 'border-primary'
                  : digit
                  ? 'border-text-primary'
                  : 'border-border'
              }`}
            >
              {digit || (isCursor ? <span className="w-0.5 h-5 bg-primary animate-pulse rounded-full" /> : '')}
            </div>
          )
        })}
      </div>
    </div>
  )
}
